kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: developer
  name: role-manager-binding
subjects:
  - kind: User
    name: {USER}
    apiGroup: ""
roleRef:
   kind: Role
   name: role-manager
   apiGroup: ""
