kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: hml
  name: deployment-manager
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["deployments", "replicaset", "pods", "*/log", "services", "endpoints"]
    verbs: ["get", "list", "watch", "patch", "update"]
