kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: read-pods
rules:
- apiGroups: [""] # “” indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
